Feature 4 test client message consuming
Metatavu/vp-kuljetus-messaging-service pull request #5
Opened 2024-08-29 04:45 UTC by villejuutila

Resolves #4

2024-08-29 07:41 UTC, anttileppa requested changes

2024-08-29 07:41 UTC, anttileppa commented on src/test/kotlin/fi/metatavu/vp/messaging/client/MessagingClient.kt
> +    private fun addIncomingMessage(routingKey: String, message: GlobalEvent) {
I would expect to find clearMessage method or design it otherwise in a way that other tests can not be affected by messages received by previous tests (e.g. getIncomingMessages would always clean the queue or segregate message receiving to another class)

2024-08-29 12:04 UTC, villejuutila commented on src/test/kotlin/fi/metatavu/vp/messaging/client/MessagingClient.kt
> +    private fun addIncomingMessage(routingKey: String, message: GlobalEvent) {
Resolved.

2024-09-02 04:06 UTC, anttileppa approved these changes

2024-09-02 05:46 UTC, merged